routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/wish', function () {
    return view('wish');
});

Route::get('/toko', function () {
    return view('toko');
});

Route::get('/tim', function () {
    return view('tim');
});


Route::get('/home', 'BukuController@index')->name('home');

Route::resource('wislist', 'wiscontroler');
Route::resource('toko', 'TokoController');
Route::resource('buku', 'BukuController');

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

resources/views/home.blade.php
@extends('master')

@section('content')


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                </div>
            </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                <img class="profile-user-img img-fluid img-circle"
                       src="{{asset('images/avatar4.png')}}"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ Auth::user()->name }}</h3>

                <p class="text-muted text-center">Software Engineer</p>

                <a href="{{route('buku.create')}}" class="btn btn-primary btn-block"><b>Tambah Buku</b></a>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <a class="card-title" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                  <h3>Koleksi Buku</h3>
              </div><!-- /.card-header -->
              <div class="card-body">
                <!-- Post -->
                @foreach($data as $key => $data)
                <div class="post">
                  <div class="user-block">
                  <img src="{{asset('/img/'.$data->gambar)}}" alt="gambar" width=25%>                    
                  <div class="username">
                      <a href="{{route('buku.show', ['buku' => $data->id])}}">{{$data->nama}}</a>
                  </div>
                  <p>{{$data->deskripsi}}</p>
                  <!-- /.user-block -->

                </div>
                <a href="buku/{{$data->id}}/edit" button class="w3-button w3-white w3-border w3-border-red w3-round-large">Edit</button>
                <form action="{{route('buku.destroy', ['buku' => $data->id])}}" method="post" style = display:inline-block;>
                        @csrf
                        @method('DELETE')
                        <input type="submit" value="Delete" class="btn btn-link">
                </form>
                @endforeach






                <!-- /.post -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
  <!-- /.content-wrapper -->
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Perpusqu Media Belajar</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('fonts/icomoon/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/animate.css')}}">
    <link rel="stylesheet" href="{{asset('css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap-datepicker.css')}}">
    
    
    <link rel="stylesheet" href="{{asset('fonts/flaticon/font/flaticon.css')}}">
  
    <link rel="stylesheet" href="{{asset('css/aos.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery.fancybox.min.css')}}">
    

    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
      <div class="flex-center position-ref full-height">
        @if (Route::has('login'))
            <div class="top-right links">
                @auth
                    <a href="{{ url('/home') }}">Home</a>
                @else
                    <a href="{{ route('login') }}">Login</a>

                    @if (Route::has('register'))
                        <a href="{{ route('register') }}">Register</a>
                    @endif
                @endauth
            </div>
        @endif
      </div>

  
  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    
    <div class="site-navbar-wrap">
      
      <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-6 col-lg-3">
              <h1 class="my-0 site-logo"><a href='/'>Perpusqu</a></h1>
            </div>
            <div class="col-6 col-lg-9">
              <nav class="site-navigation text-right" role="navigation">
                <div class="container">

                  <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3 "><a href="#" class="site-menu-toggle js-menu-toggle text-black">
                    <span class="icon-menu h3"></span>
                  </a></div>

                  <ul class="site-menu main-menu js-clone-nav d-none d-lg-block">
                    @if (Route::has('login'))
                      @auth
                        <li><a href="{{ url('/home') }}" class="nav-link">Home</a></li>
                      @else
                        <li><a href="{{ route('login') }}">Login</a></li>
                        @if (Route::has('register'))
                          <li><a href="{{ route('register') }}">Register</a></li>
                        @endif
                      @endauth
                    @endif
                    <li><a href="/tim" class="nav-link">About Us</a></li>

                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- END .site-navbar-wrap -->
    
    

    <div class="site-section" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mb-5">
            <h1 class="text-white serif text-uppercase mb-4">Terhubung dengan informasi bermanfaat</h1>
            <p class="text-white mb-5">Berkarya,berinovasi, berbagi ilmu! </p>
            <p><a href="{{ route('login') }}" class="btn btn-white px-4 py-3">Bergabung bersama kami</a></p>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-10">
            <img src="images/book_1.png" alt="Image" class="img-fluid">
          </div>
        </div>
      </div>
    </div>

  
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-12">
                <h3 class="footer-heading mb-4">About Us</h3>
                <ul class="list-unstyled">
                  <li><a href="https://gitlab.com/firmanzy">Muhamad Firmansyah </a></li>
                  <li><a href="https://gitlab.com/sahadat16021293">Sahadat Islam</a></li>
                  <li><a href="https://gitlab.com/yudisyudis">Yudisthira Iriana Putra</a></li>
                </ul>
              </div>
            </div>
            

            
          </div>
          <div class="col-lg-3 ml-auto">
           
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigation</h3>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="/">Home</a></li>
                  <li><a href="/tim" >Team</a></li>
                </ul>
              </div>
              
            </div>
            
          </div>
          

          <div class="col-lg-4 mb-5 mb-lg-0" id="contact-section">

            <div class="mb-5">
              <h3 class="footer-heading mb-4">Quick Contact</h3>
                <div class="toast-body">
                  <p> Hello, friend. Please reach Us on Gitlab for inquiries </p>
                  <p> Link on About Us page </p>

                </div>

            </div>

            


          </div>
          
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="mb-4">
                  <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                </div>
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>

  <script src="js/jquery-3.3.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/jquery.sticky.js"></script>
  <script src="js/stickyfill.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/isotope.pkgd.min.js"></script>
  
  <script src="js/jquery.fancybox.min.js"></script>
  <script src="js/main.js"></script>

     
  </body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Perpusqu Media Belajar</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('fonts/icomoon/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/animate.css')}}">
    <link rel="stylesheet" href="{{asset('css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap-datepicker.css')}}">
    <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">

    
    
    <link rel="stylesheet" href="{{asset('fonts/flaticon/font/flaticon.css')}}">
  
    <link rel="stylesheet" href="{{asset('css/aos.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery.fancybox.min.css')}}">
    {{-- css boostrap --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  
  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    
    <div class="site-navbar-wrap">
      
      <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-6 col-lg-3">
              <h1 class="my-0 site-logo"><a href='/'>Perpusqu</a></h1>
              @include('sweetalert::alert')
            </div>
            <div class="col-6 col-lg-9">
              <nav class="site-navigation text-right" role="navigation">
                <div class="container">

                  <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3 "><a href="#" class="site-menu-toggle js-menu-toggle text-black">
                    <span class="icon-menu h3"></span>
                  </a></div>

                  <ul class="site-menu main-menu js-clone-nav d-none d-lg-block">
                    @if (Route::has('login'))
                      @auth
                      <li ><a href="{{ url('/home') }}" class="nav-link">Home</a></li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="{{ url('/home') }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre><span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                      @else
                        <li><a href="{{ route('login') }}">Login</a></li>
                        @if (Route::has('register'))
                          <li><a href="{{ route('register') }}">Register</a></li>
                        @endif
                      @endauth
                    @endif
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                        Wishlist Buku
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/wislist/create">Tambah Wishlist</a>
                      </div>
                    </li>
                    <li><a href="/tim" class="nav-link">About Us</a></li>
                    {{-- <li><a href="/wislist" class="nav-link">Wishlist Buku</a></li> --}}
                    <li><a href="/toko" class="nav-link">Toko Buku</a></li>



                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- END .site-navbar-wrap -->
    
    

    <div class="site-section" id="home-section">
    @yield('content')
    </div>

  
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-12">
                <h3 class="footer-heading mb-4">The Developers</h3>

                <ul class="list-unstyled">
                  <li><a href="https://gitlab.com/firmanzy">Muhamad Firmansyah </a></li>
                  <li><a href="https://gitlab.com/sahadat16021293">Sahadat Islam</a></li>
                  <li><a href="https://gitlab.com/yudisyudis">Yudisthira Iriana Putra</a></li>
                </ul>
              </div>
            </div>
            

            
          </div>
          <div class="col-lg-3 ml-auto">
           
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigation</h3>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href='/'>Home</a></li>
                  <li><a href="/tim" >Team</a></li>
                </ul>
              </div>
              
            </div>
            
          </div>
          

          <div class="col-lg-4 mb-5 mb-lg-0" id="contact-section">

            <div class="mb-5">
              <h3 class="footer-heading mb-4">Quick Contact</h3>
                <div class="toast-body">
                  <p> Hello, friend. Please reach Us on Gitlab for inquiries </p>
                  <p> Link on About Us page </p>

                </div>
            </div>

            


          </div>
          
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="mb-4">
                  <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                </div>
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Tim 6 Full Stack Web Development <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>

  <script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
  <script src="{{asset('js/popper.min.js')}}"></script>
  <script src="{{asset('js/bootstrap.min.js')}}"></script>
  <script src="{{asset('js/owl.carousel.min.js')}}"></script>
  <script src="{{asset('js/aos.js')}}"></script>
  <script src="{{asset('js/jquery.sticky.js')}}"></script>
  <script src="{{asset('js/stickyfill.min.js')}}"></script>
  <script src="{{asset('js/jquery.easing.1.3.js')}}"></script>
  <script src="{{asset('js/isotope.pkgd.min.js')}}"></script>
  
  <script src="{{asset('js/jquery.fancybox.min.js')}}"></script>
  <script src="{{asset('js/main.js')}}"></script>
  {{-- java skrip boostrap --}}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  </body>
</html>

resources/views/tim.blade.php
@extends('master')
@section('content')
    <div class="card" style="margin-top:0px; width: 75rem; height:15rem; margin-left:30px">
        <div class="card-header font-weight-bold text-center">
            <h1>Tim Kami</h1>
        </div>

        <div class="container " style="margin-bottom: 250px; margin-left:50px; padding: 0px 25px 0px 25px">
            <div class="row">
                <div class="col-sm">
                    <img class="ml-lg-4" src="{{ asset('img/profile-tim.jpg') }}" width="30%">
                    <h6 class="">Muhamad Firmansyah </h6>
                    <p class="ml-lg-4">"Web Developer"</p>
                </div>
                <div class="col-sm">
                    <img class="ml-lg-3" src="{{ asset('img/profile-tim.jpg') }}" width="30%">
                    <h6 class="ml-md-3">Sahadat Islam</h6>
                    <p class="ml-lg-3">"Web Developer"</p>
                </div>
                <div class="col-sm">
                    <img class="ml-lg-4" src="{{ asset('img/profile-tim.jpg') }}" width="30%">
                    <h6 class="ml-md-3">Yudisthira Iriana Putra</h6>
                    <p class="ml-md-4">"Web Developer"</p>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/toko.blade.php
@extends('master')

@section('create')
<a href="/toko/create" style="float: right"><button type="button" class="btn btn-light mt-1 mb-2" ><i class="fa fa-plus" aria-hidden="true"></i>
    Menambahkan toko</button></a>
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="{{asset('images/avatar4.png')}}"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ Auth::user()->name }}</h3>

                <p class="text-muted text-center">Uploader</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <a class="card-title" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
<div class="container">

<a class="btn btn-light mb-2" href="/toko/create">Menambahkan Toko</a>
      <table class="table table-bordered table-dark">
        <thead>
            @if (!empty($listtoko[0]))
            <tr>
            <th style="width: 50px">#</th>
            <th style="width: 400px">Nama Toko</th>
            <th>Alamat</th>
            <th style="width: 200px">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($listtoko as $indexArr => $toko)
              <tr>
                  <td>{{$indexArr + 1 }}</td>
                  <td>{{$toko -> nama_toko }}</td>
                  <td>{{$toko -> alamat }}</td>
                  <td style="display: flex;">
                      <a href="/toko/{{$toko->id}}" class="btn btn-info text-light mx-1"><i class="fas fa-eye"></i></a>
                      <a href="/toko/{{$toko->id}}/edit" class="btn btn-warning mx-1"><i class="far fa-edit"></i></a>
                      <form action="/toko/{{$toko->id}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button input type="submit" class="btn btn-outline-danger mx-1" value="delete">
                        <i class="far fa-trash-alt"></i></button>

                      </form>
                  </td>
              </tr>
          @endforeach
          @else
          <tr>
            <td colspan="5" align="center">No toko Data</td> 
          </tr>
          @endif
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/wish.blade.php
@extends('master')

@section('content')
@endsection