routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/wish', function () {
    return view('wish');
});

Route::get('/toko', function () {
    return view('toko');
});

Route::get('/tim', function () {
    return view('tim');
});


Route::get('/home', 'BukuController@index')->name('home');

Route::resource('wislist', 'wiscontroler');
Route::resource('toko', 'TokoController');
Route::resource('buku', 'BukuController');

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use DB;

class BukuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Book::all();
        return view('home', compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('/buku/create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nama = $request -> gambar;
        $namaFile = $nama -> getClientOriginalName();
 
        $upload = DB::table('books')->insert([
         'nama' => $request['nama'],
         'deskripsi' => $request['deskripsi'],
         'gambar' => $namaFile,
        ]);
 
        $nama -> move (public_path().'/img', $namaFile);
 

        return redirect('/buku');





    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data1 = DB::table('books')->where('id',$id)->first();        
        return view('/buku/show', compact('data1'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data2 = Book::where('id', $id)->first();
        return view('/buku/edit', compact('data2'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nama = $request -> gambar;
        $namaFile = $nama -> getClientOriginalName();

        $update = DB::table('books')

              ->where('id', $id)
              ->update([
                  'nama' => $request['nama'],
                  'deskripsi' => $request['deskripsi'],
                  'gambar' => $namaFile
                ]);
                $nama -> move (public_path().'/images', $namaFile);
        return redirect('/buku')->with('success', 'berhasil update');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::destroy($id);
        return redirect('/buku');

    }
}

resources/views/buku/create.blade.php
@extends('master')

@section('content')
<div class="container h-50">
    <div class='form'>
        <form action="{{route('buku.index')}}" method='POST' enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="nama"><h5>Nama Buku</h5></label>
                <input type="text" class="form-control" id="nama" name='nama' placeholder="Nama Buku">
            </div>

            <div class="form-group">
                <label for="deskripsi"><h5>Deskripsi</h5></label>
                <textarea class="form-control" id="deskripsi" name='deskripsi' rows="5"></textarea>
            </div>

            <div class="form-group">
                <label for="gambar"><h5>Gambar</h5></label>
                <br>
                <input id="gambar" name="gambar" type="file" class="file" data-browse-on-zone-click="true">
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
</div>

    
@endsection

resources/views/buku/edit.blade.php
@extends('master')

@section('content')
<div class="container h-50">
    <div class='form'>
        <form action="/buku/{{$data2->id}}" method='POST' enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="form-group">
                <label for="nama"><h5>Nama Buku</h5></label>
                <input type="text" class="form-control" id="nama" name="nama" placeholder="Nama Buku" value="{{old('nama', $data2-> nama )}}">
            </div>

            <div class="form-group">
                <label for="deskripsi"><h5>Deskripsi</h5></label>
                <textarea class="form-control" id="deskripsi" name='deskripsi' rows="5"></textarea>
            </div>

            <div class="form-group">
                <label for="gambar"><h5>Gambar</h5></label>
                <br>
                <input id="gambar" name="gambar" type="file" class="file" data-browse-on-zone-click="true">
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
</div>

    
@endsection

resources/views/buku/show.blade.php
@extends('master')

@section('content')
<div class="card-body">
    <div class="post">
        <div class="col d-flex justify-content-center">

            <div class="user-block">
                <h5>{{$data1->nama}}</h5>

                <img src="{{asset('/img/'.$data1->gambar)}}" alt="gambar" width=25%> 
                <h3>{{$data1->deskripsi}}</h3> 
            </div>                  
        </div>
    </div>
</div>

@endsection